Input data
lambdaclass/madara_explorer pull request #142
Opened 2023-09-13 15:21 UTC by ElFantasma

Completing input data for simple transactions

2023-09-14 15:12 UTC, SantiagoPittella requested changes

2023-09-14 15:12 UTC, SantiagoPittella commented on lib/starknet_explorer/data.ex
> +                        class["abi"],
this fails with the Cairo0 ABIs, since those are encoded.
You could check if class["abi"] is map, if not then call to `Jason.decode/1`.

2023-09-14 17:45 UTC, igaray approved these changes

2023-09-15 17:44 UTC, igaray approved these changes

2023-09-15 17:56 UTC, SantiagoPittella approved these changes

2023-09-15 18:00 UTC, merged